### ISSUE TITLE
minimal arch.make doesn't work

### ISSUE THREAD

**Issue by nicoduchene** [ElectronicStructureLibrary/flook#3]
After trying to compile flook on linux with the minimal arch.make, I get:

> gfortran -c -o flu_binding.o  -Iexternal/lua-5.3.4/src ../.././aotus/LuaFortran/flu_binding.f90
> ../.././aotus/LuaFortran/flu_binding.f90:633.20:
> 
>     c_fn = c_funloc(fn)
>                     1
> Error: Parameter 'fn' to 'c_funloc' at (1) must be BIND(C)
> make[1]: *** [flu_binding.o] Error 1
> make[1]: Leaving directory `/home/niduc/SIESTA/flook/aotus/obj'
> make: *** [lib-aotus] Error 2
> 

The gfortran version is : 

> GNU Fortran (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)

Is my problem linked to the compiler or is it something else?

Cheers,
Nicolas

**Comment by zerothi** [comment]
I guess the 4.4.6 version doesn't recognize the `bind(c)` in the abstract interface.

I think you should update the compiler version.

**Comment by nicoduchene** [comment]
That was it. 
Thanks for your confirmation.
