### ISSUE TITLE
make check

### ISSUE THREAD

**Issue by brandimarte** [ElectronicStructureLibrary/flook#5]
Hi again!

I think I managed to generate the libraries but I was not able to run the tests. Is it missing in the main Makefile?

Best!

**Comment by zerothi** [comment]
Currently the tests haven't been migrated to the new build-system.

However, if you can compile the program I can't see why they won't pass. They are truly simple, in the most generic sense. So you should be fine. :)

**Comment by zerothi** [comment]
I will try, when I get the time, to fix this issue.

**Comment by zerothi** [comment]
Fixed in #453a5d7b090a15f4f29954f0bcc3617b0b31c652, finally!
