### ISSUE TITLE
Cannot switch compiler to intel in ESL bundle

### ISSUE THREAD

**Issue by ocaisa** [ElectronicStructureLibrary/flook#7]
I was trying to build the ESL bundle with the intel compiler and Flook is causing me problems when linking the demonstrator since it can't read the mod files generated by the GCC compiler used by Flook. Flook seems to ignore all of the typical environment variables (`CC`, `FC`, `CFLAGS`). It also seems that `aotus` requires an additional `VENDOR=intel` argument for intel compilers.

Any tips to make this work?

**Comment by zerothi** [comment]
Both `flook` and `aotus` requires the `VENDOR=intel` flag, that should work.

**Comment by zerothi** [comment]
Yeah, I agree I really need to fix the build system... It is just a mess with aotus which has the Lua sources shipped. Secondly, aotus has its own build-system (`waf`). So it is a bit tricky to streamline this... :(

**Comment by ocaisa** [comment]
The lua stuff is not too bad since it all C, so I can still link just fine. It's the fortran that's the problem because I need the `.mod` files with the right compiler.

**Comment by zerothi** [comment]
Agreed, but it was more in terms of me doing another build-system. Then I need to create a build-system which uses different sub-build systems... :(

Well, just a complaint ;)

**Comment by zerothi** [comment]
Actually the easiest is to do:
1. Create an `obj` directory
2. Create a `setup.make` file with this content:
```bash
CC = icc
FC = ifort
```
3. Create a file `Makefile` with this content:
```bash
TOP_DIR =..
include ../Makefile
```
4. Run `make liball`
5. Run `make install PREFIX=...`

This should suffice, also for intel! :)

**Comment by ocaisa** [comment]
Yes, that works...now I just need to figure out how to tell the ESL bundle to do that!

**Comment by micaeljtoliveira** [comment]
@ocaisa Sorry for the very late reply.

> Yes, that works...now I just need to figure out how to tell the ESL bundle to do that!

That should not be too difficult, as one can tell jhbuild to apply a patch. I will create an issue for this.

**Comment by zerothi** [comment]
Great! I'll close this for now.
